version: 2
jobs:
  build:
    docker:
      # Use LTS node CircleCI image: has node, python2 and python3
      - image: circleci/golang:1.11.4-stretch
    working_directory: /go/src/github.com/evanj/googlesignin
    steps:
      - checkout
      - run:
          name: run tests
          command: ./circleci.sh
