version: 2
jobs:
  build:
    docker:
      - image: golang:1.13.3-buster
    working_directory: /go/src/github.com/evanj/googlesignin
    steps:
      - checkout
      - run:
          name: run tests
          command: ./circleci.sh
